// GENERADO por scripts/subset-iconos.mjs — no editar a mano.
// Codepoint de cada icono de ICONOS (iconos.ts) dentro del subconjunto
// embebido de Material Symbols Rounded. Regenerar con: npm run gen:iconos
import type { IconoNombre } from './iconos';

export const CODEPOINTS: Record<IconoNombre, string> = {
  add: '\u{E145}',
  arrow_back: '\u{E5C4}',
  assignment_ind: '\u{E85E}',
  block: '\u{E033}',
  check: '\u{E5CA}',
  check_circle: '\u{E86C}',
  chevron_left: '\u{E408}',
  chevron_right: '\u{E409}',
  close: '\u{E14C}',
  delete: '\u{E872}',
  description: '\u{E873}',
  done_all: '\u{E877}',
  download: '\u{E171}',
  edit: '\u{E150}',
  error: '\u{E000}',
  expand_more: '\u{E5CF}',
  fact_check: '\u{F0C5}',
  folder_open: '\u{E2C8}',
  folder_zip: '\u{EB2C}',
  gavel: '\u{E90E}',
  groups: '\u{F233}',
  history: '\u{E28E}',
  home: '\u{E88A}',
  info: '\u{E88E}',
  key_off: '\u{EB84}',
  lock: '\u{E88D}',
  logout: '\u{E9BA}',
  map: '\u{E55B}',
  menu: '\u{E5D2}',
  payments: '\u{EF63}',
  pending_actions: '\u{F1BB}',
  person_add: '\u{E7FE}',
  plumbing: '\u{F107}',
  print: '\u{E555}',
  public: '\u{E80B}',
  radio_button_unchecked: '\u{E836}',
  receipt: '\u{E8B0}',
  receipt_long: '\u{EF6E}',
  refresh: '\u{E5D5}',
  restart_alt: '\u{F053}',
  save: '\u{E161}',
  schedule: '\u{E192}',
  search_off: '\u{EA76}',
  send: '\u{E163}',
  settings: '\u{E8B8}',
  shield: '\u{E9E0}',
  summarize: '\u{F071}',
  task_alt: '\u{E2E6}',
  timer_off: '\u{E426}',
  upload: '\u{E2C6}',
  verified: '\u{E031}',
  visibility: '\u{E417}',
  warning: '\u{E002}',
  water_drop: '\u{E798}',
  workspace_premium: '\u{E7AF}',
};
